"""add updated time

Revision ID: 056d09cd1c08
Revises: 
Create Date: 2021-07-31 16:53:38.242290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056d09cd1c08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solditems', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('solditems', sa.Column('updated_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solditems', 'updated_time')
    op.drop_column('solditems', 'created_date')
    # ### end Alembic commands ###
